USE wechat;

DROP TABLE StockChange;

CREATE TABLE StockChange (
    ID INT AUTO_INCREMENT,
    StockPrice VARCHAR(255),
    ChatCounts VARCHAR(255),
    Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

