CREATE DATABASE wechat;
USE wechat;

DROP TABLE StockChange IF EXISTS;

CREATE TABLE GroupChat (
    ID INT AUTO_INCREMENT,
    GroupName VARCHAR(255),
    SenderName VARCHAR(255),
    MessageContent TEXT,
    SendTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);


CREATE TABLE StockChange (
    ID INT AUTO_INCREMENT,
    StockPrice VARCHAR(255),
    ChatCounts VARCHAR(255),
    Time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

